- lib/seo.php
Hi,
wir haben gerade bemerkt dass die hreflang immer nur auf die Startseite referenziert und dies angepasst dass es die jeweilige Artikel-Url zurückgibt.
Zudem habe ich eine Überprüfung auf Online/offline eingebaut und einen Extension-Point registriert um für custom Urls (Frau Schulze) einen Hook zu haben.
lg
alex
> HreflangTag geändert + extension point hinzugefügt

- boot.php
> korrekter Pfad auf Windows Servern

- lib/domain.php
- lib/yrewrite.php
> Nur aktive Sprachen berücksichtigen

- lib/domain.php
- lib/yrewrite.php
Reverts yakamara/redaxo_yrewrite#174
> Revert "Nur aktive Sprachen berücksichtigen"

- setup/.htaccess
Hat keine Auswirkungen, ist nur Kosmetik.
> dots bei den Dateiendungen angeglichen

- boot.php
- lib/yrewrite.php
closes #57, #167 und halb #190
> Neue Extension Points ART_MOVED und ART_COPIED

- pages/docs.php
> Korrektur .htaccess-Erstellung

- package.yml
Vorschlag für Vereinheitlichung
> Doku / Hilfe-Tab rechts

- lib/yrewrite.php
Reported in Slack:
Notice	Undefined variable: params	redaxo/src/addons/yrewrite/lib/yrewrite.php 276
Ungetestet
> Fixed warning

- package.yml
Closes https://github.com/yakamara/redaxo_yrewrite/issues/270
Ich hab nicht geprüft ob/warum php7 gebraucht wird.. habe das issue für bare Münze genommen
> min php7.0 in package.yml ergänzt

- boot.php
- lib/yrewrite.php
> MediaManager-URLs umschreiben

- lib/yrewrite.php
> add better query_string check

- README.md
> Mount-Artikel besser erläutern

- README.md
Via Slack-Diskussion aufgefallen.
> Hinweis zur .htaccess in Kombination mit Ressourcen im Media-Ordner

- README.md
> Doku um Beispiel für eigenes Schema erweitert

- README.md
Übertrag aus:
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/addons/yrewrite/nginx.md
Danke @Hirbod
> NGINX-Konfiguration für YRewrite

- boot.php
Siehe auch https://github.com/redaxo/redaxo/pull/3293
> Media-Manager-URLs auch im Backend umschreiben

- install.php
- lang/de_de.lang
- lang/en_gb.lang
- lib/yrewrite/domain.php
- lib/yrewrite/scheme.php
- lib/yrewrite/yrewrite.php
- pages/domains.php
closes #340
Es ist meine im Issue vorgeschlagene recht simple Lösung.
**ACHTUNG**: Dieser PR benötigt #343. Falls der PR nicht reingenommen wird, müsste hier im PR noch was geändert werden.
> Start-Clang optional automatisch gemäß Browsersprache

- lib/yrewrite/yrewrite.php
> Default-Domain: Sprache nicht mit in Domain, wenn nur eine Sprache

- .github/workflows/phpstan.yml
should fix https://github.com/yakamara/redaxo_yrewrite/pull/376#issuecomment-724720293
> use checkout without token, to make the workflow work in forks

- README.md
Aus Slack: 
Danke an: Markus Weiss
>… mir aber aufgefallen, dass die aktuellsten Links des Media-Managers noch nicht funktionieren. Zu den Rewrite-Rules muss noch folgende hinzugefügt werden. Dann werden die Vorschaubilder angezeigt 👍
> Adding nginx Rewrite-Rule

- package.yml
closes: https://github.com/yakamara/redaxo_yrewrite/issues/426
> require structure-Addon

- lib/yrewrite/path_generator.php
- lib/yrewrite/path_resolver.php
- lib/yrewrite/yrewrite.php
closes #387 
Dieser PR setzt das um, was ich im verlinkten PR beschrieben habe: https://github.com/yakamara/redaxo_yrewrite/pull/387#issuecomment-742487753
Kann das jemand testen?
> Weiterleitungen: Direktaufruf originaler URL ermöglichen

- lib/yrewrite/path_resolver.php
Fix #405. Eine Weiterleitung zu einer Sprache die Offline ist wird verhindert.
> Weiterleitung zu offline Sprache verhindern

- lib/yrewrite/yrewrite.php
> Config-File: Opcache invalidieren

- lib/yrewrite/path_resolver.php
Teilrevert von https://github.com/yakamara/redaxo_yrewrite/pull/442
> fix compat

- lib/yrewrite/forward.php
> Weiterleitungen case-insensitive

- lib/yrewrite/yrewrite.php
> getFullPath im Backend korrigiert

- lib/yrewrite/path_resolver.php
> Notice vermeiden

- CHANGELOG.md
- package.yml
> Release 2.8.3

- README.md
> Protokollwechsel erwähnen

- README.md
> Hinweis zu mehrsprachigen Websites und Domains

- lib/yrewrite/forward.php
> Weiterleitungen: URL-kodierte  Pfade unterstützen

- README.md
- docs/README.en_gb.md
die vorherigen Methoden sind deprecated
> Readme Methode getTags() aktualisiert

- lib/yrewrite/path_resolver.php
> Wenn Host fehlt, dann Default-Domain

- install.php
- lib/yrewrite/yrewrite.php
- package.yml
- pages/forward.php
- update.php
* Feld ist nullable, kein `0000-00-00` mehr
* Deaktivierungsdatum kann selbst gesetzt/geändert werden, closes #335
> Weiterleitungen: Optimierungen Deaktivierungsdatum

- lib/yrewrite/yrewrite.php
> Weiterleitung bei Aufruf per ?article_id=X

- install.php
- lib/yrewrite/seo.php
- update.php
> SEO: Default-Werte korrekt berücksichtigen

- README.md
Copy and Paste in NGINX Config without conflicts
> Changing Comments to Hash sign

- assets/xsl-stylesheets/xml-sitemap.xsl
- lib/yrewrite/seo.php
Ich brauche den Patch für Erweiterungen in einigen Addons von mir (d2u_videos, d2u_machinery, ...)
> Videos in Sitemap ermöglichen

- lib/yrewrite/seo.php
Ohne Break werden alle Sprachen der gleichen MountID als hreflang aufgenommen
fixes #530
> Sprachen gleicher MountID Domainübergreifend als hreflang Tag

- README.md
- docs/README.en_gb.md
- lib/yrewrite/seo.php
> meta und link tags nicht schließen

- lib/yrewrite/forward.php
fixes #508
/cc @michael-kreatif
> Weiterleitungen: Params ohne Werte unterstützen

- lib/yrewrite/seo.php
> SEO Tags: "noindex, follow" wurde nicht berücksichtigt

- pages/setup.php
Hallo zusammen,
hier der PR für DE und EN zum issue #537 
closes #537
> Doku aktualisieren deprecated seo gedöns (setup)

- lib/yrewrite/yrewrite.php
> Fix Warning in yrewrite.php

- lib/yrewrite/yrewrite.php
> Fix warnings "undefined array key"
