- lang/de_de.lang
- lang/en_gb.lang
- lib/forward.php
- pages/forward.php
Es kommt vor, dass eine url nach einem Umzug vorhanden bleiben soll, aber erst später eine eigene Seite und eigene Inhalte bekommt. Es soll also keine Weiterleitung erfolgen, aber ein temporärer Inhalt unter der originalen url angezeigt werden. Das kann mit dieser zusätzlichen Auswahlmöglichkeit erfüllt werden. Daher wäre ich für eine Übernahme ausgesprochen dankbar :-)
> 302 ergänzt

- pages/forward.php
Ermöglicht, nur ein Zeichen in der URL einzugeben, das nicht mit einem Slash beginnt. Slash am Ende wird dennoch geblockt.
close #204
> URL-Matching

- lang/de_de.lang
- lang/en_gb.lang
- lib/forward.php
- pages/forward.php
Die Liste der Weiterleitungen wurde um den Statuscode ergänzt. Zusätzlich wurden die Sortierfunktionen über rex_list eingeschaltet. Damit kann man die Übersicht nach Statuscode, aktiv/inaktiv, url und id sortieren, was bei längeren Weiterleitungsliste erhebliche Vorteile bei der Bearbeitung bringt.
> Liste Weiterleitungen

- lib/yrewrite.php
U.a. wurde der NotFoundArticle immer in der clangId=1 ausgeliefert
> Korrekte clangId setzen

- lang/de_de.lang
https://www.duden.de/rechtschreibung/indexieren
(Fachsprache) einen Index (1), eine Liste von Gegenständen oder Hinweisen anlegen
https://www.duden.de/rechtschreibung/indizieren
(ein Druckwerk) in eine Liste von Schriften aufnehmen, deren Verbreitung an Jugendliche untersagt ist, weil sie als jugendgefährdend gelten
siehe auch: https://de.wikipedia.org/wiki/Indexierung
Muss m.E. nicht in YTraduco neu übersetzt werden, da nur die dt. Übersetzung falsch ist.
> Indizierung -> Indexierung

- package.yml
- pages/domains.php
Die beiden select_sql Felder wurden durch Choice Felder ersetzt. Grund. Die Mehrfahrauswahl des "clangs" Feldes wurden mit YForm 3 nicht mehr gespeichert.
> select_sql entfernt

- install.php
Wenn ich einen Artikel mit chinesischen Zeichen in YRewrite 2.5 umbennen und eine Weiterleitung automatisch angelegt werden soll erhalte ich folgenden Fehler:
PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' in /www/htdocs/redaxo/src/core/lib/sql/sql.php:296 Stack trace: #0 /www/htdocs/redaxo/src/core/lib/sql/sql.php(296): PDOStatement->execute(Array) #1 /www/htdocs/redaxo/src/core/lib/sql/sql.php(341): rex_sql->execute(Array, Array) #2 /www/htdocs/redaxo/src/core/lib/sql/sql.php(938): rex_sql->setQuery('DELETE FROM `re...', Array) #3 /www/htdocs/redaxo/src/addons/yrewrite/lib/yrewrite.php(605): rex_sql->delete() #4 /www/htdocs/redaxo/src/addons/yrewrite/boot.php(44): …
> utf8mb4 Umstellung

- install.php
Beim Aufruf während des Updates ist die Klasse noch nicht im Autoloader vorhanden. Dies sollte das Problem beheben.
> Neue Klasse manuell einbinden, fixes #292

- lib/yrewrite/yrewrite.php
Im Moment erzeugt mir yrewrite ohne eingetragene domain (also mit der "default") auf meinem Windows-Rechner Links der Form `http://abcd.local\/`
Im Fix nutze ich "DIRECTORY_SEPARATOR" im rtrim.
Das ist die letzte Stelle, wo ein Dateipfad genutzt wird - alles andere sind URLs. Da reicht den slash rausfiltern. An einer anderen Stelle ist auch die Konstante im Einsatz.
> Windows Rechnern ermöglichen, dass die "default"-domain funktioniert

- README.md
Mir @Hirbod im Slack besprochen: Die betroffenen Regeln stammen noch aus einer früheren Version und sind hier obsolet. Sie haben gar keine Auswirkungen auf die Konfiguration und können dementsprechend entfernt werden.
> README: NGINX-Konfiguration angepasst

- lang/de_de.lang
- lang/en_gb.lang
- lang/es_es.lang
- lang/pt_br.lang
- lang/sv_se.lang
- lib/yrewrite/seo.php
- pages/content.yrewrite_seo.php
Seo Option '<.meta name="robots" content="noindex, follow">' hinzugefügt.
(der Punkt vor Meta weil sonst als HTML gerendert)
Dazu kein Eintrag in sitemap.xml.
Übersetzungen aus vorhandenen Einträgen und Google Translate.
Meta Tag und Sitemap wurden getestet.
> Seo Option 'noindex,follow'

- README.md
Es ist immer nur ein Schema erlaubt.
XCore wird nicht mehr empfohlen, daher hier raus.
> Schemes in Schema umbenannt, Hinweis auf XCore entfernt

- lib/yrewrite/scheme.php
- package.yml
- update.php
Aktuell ist es so, dass wenn nur eine Sprache existiert, oder nur eine Sprache für eine Domain ausgewählt wurde, die Checkbox "Startsprache nicht mit in URL" keine Auswirkung hat, die Startsprache ist dann niemals mit in der URL.
Ich schlage vor es so zu ändern, dass auch dann die Checkbox eine Auswirkung hat. So kann man auch bei nur einer Sprache diese mit in die URL bekommen, zum Beispiel als Vorplanung, falls irgendwann weitere Sprachen hinzukommen.
Beim Update werden alle vorhandenen Domains entsprechend angepasst, damit sie sich genauso verhalten, wie vorher.
> Auch bei nur einer Sprache diese mit in URL (wenn clang_start_hidden=0)

- lib/yrewrite/yrewrite.php
Die bleiben ja sowieso auf der aktuellen Domain.
Ist nötig als Fix für https://github.com/redaxo/redaxo/issues/3681. Ansonsten wurde [hier](https://github.com/redaxo/redaxo/blob/afb1650b13b81235a7236ab838e216882dca917d/redaxo/src/addons/structure/plugins/history/boot.php#L34) immer ausgeloggt, wenn man in yrewrite keine Domain angelegt hat.
> Bei Artikeln aus Default-Domain relative URLs erzeugen

- boot.php
- lib/yrewrite/yrewrite.php
closes #325
Mit diesem PR greifen im Backend sowohl die expliziten Alias-Domains, als auch die impliziten Umleitungen zwischen http und https, bzw. www und non-www.
@dergel Nicht blind mergen, sondern auch nochmal drüber nachdenken, ob es so passt.
Bei meinen lokalen Tests sah es aber gut aus.
> Auch im Backend Domain-Aliase umleiten

- lib/yrewrite/yrewrite.php
Bei Domains mit subfolder wurde die sitemap.xml nicht richtig generiert:
Dieser Fix behebt das Problem #306
> Korrigiert bei Domains mit subfolder die Sitemap

- install.php
- lang/de_de.lang
- lang/en_gb.lang
- lang/es_es.lang
- lang/sv_se.lang
- lib/yrewrite/scheme.php
- lib/yrewrite/settings.php
- pages/setup.php
Mit diesem PR wird es in yrewrite eine globale Einstellung geben, ob Unicode-URLs verwendet werden sollen.
Default ist die vorerst nicht aktiviert, langfristig wollen wir das aber ändern.
Ich bin mir noch nicht 100% sicher, welche Zeichen genau in dem Modus dann trotzdem noch ersetzt werden sollen, und welche erhalten bleiben sollen.
Aktuell ist im PR das Verhalten so:
- Großbuchstaben werden zu Kleinbuchstaben (finde ich in URLs schöner)
- Apostrophe werden ersatzlos gelöscht (`don't` wird zu `dont` etc.)
- Ansonsten werden alle Zeichen durch "-" ersetzt, außer diese:
- Unicode-Letters (also normale Schriftzeichen inkl. Umlaute, chinesische/kyrillische Zeichen etc.)
- Zahlen
- Währungszeichen ($, € etc.)
- Mehrfache "--" werden zu einem "-", und "-" am Anfang/Ende werden entfernt …
> Optional Unicode-URLs unterstützen

- .github/workflows/chatops.yml
- .github/workflows/phpstan.yml
phpstan handling passiert nur noch in den Pull Requests, nicht mehr lokal. d.h. um eine baseline neu in einem pull-request zu generieren schreibt man im Pull Request den kommentar /phpstan-baseline. dadurch wird eine GitHub Action getriggert, die die baseline neu generiert (alle errors die im PR noch vorhanden sind, landen auf der ignore-list bzw. errors die ggf. nicht mehr vorhanden sind werden aus der baseline entfernt).
> Add chatops phpstan-baseline command

- lib/var/yrewrite_domain.php
closes #398
`REX_YREWRITE_DOMAIN[field="id"]`
Felder können sein: id, mount_id, name, host, start_id, not_found_id, clang, url, path, robots
> rex_var_yrewrite_domain ergänzt

- install.php
fixes #448
Ich beschränke die Spalten nun doch wieder, aber auf 512.
Und den Unique Key nehme ich trotzdem erstmal wieder weg. Ich glaube nicht, dass es überall funktionieren würde mit 512.
Ich finde es auch schade, den Unique Key zu verlieren. Aber ich habe jetzt gerade keine Zeit, mich damit genauer zu beschäftigen, und möchte gerne das Release fixen.
> Fix unique key error

- install.php
- lib/yrewrite/seo.php
2 Änderungen:
- Standardeffekt skaliert das Bild auf die maximale Seitenlänge 4096x4096px um der maximalen Twitter Bildgröße zu entsprechen
- Twitter Tags werden nicht über das Attribut "property" sondern "name" ausgegeben.
> Standardeffekt Skalieren hinzugefügt

- lang/de_de.lang
- lang/en_gb.lang
- pages/forward.php
Damit werden die Weiterleitungsziele in der Übersichtsliste angezeigt. 
Das hilft z.B. dabei, gelöschte Artikel oder Medien zu identifizieren.
> Weiterleitungen: Spalte zur Anzeige der Weiterleitungsziele

- setup/.htaccess
Die Browser Tools im Edge gaben mir den Hinweis, dass die per .htaccess gesetzten mime-types nicht mehr stimmen...
AddType application/font-woff .woff --->	AddType font/font-woff .woff
und
AddType application/javascript .js ---> AddType text/javascript .js
> update mime types

- lib/yrewrite/yrewrite.php
Prüft, ob ein Artikel existiert, bevor auf ihn umgeleitet wird. Fix https://github.com/yakamara/redaxo_yrewrite/issues/498
> Umleitungsschleife beheben

- lib/yrewrite/path_resolver.php
- lib/yrewrite/seo.php
closes #511
In dem Issue war aufgefallen, dass wir bei der automatischen Startseiten-Sprachweiterleitung (gemäß Browsersprache) noch nicht `x-default` als hreflang setzen.
https://developers.google.com/search/blog/2013/04/x-default-hreflang-for-international-pages?hl=de
Neu liefert nun `rex_yrewrite_seo::getHrefLangs` auch den Wert für `x-default`, wenn man sich auf der Startseite befindet und für die Domain die automatische Sprachweiterleitung eingerichtet wurde.
Auf den einzelnen Sprach-Startseiten ist man weiterhin selbst verantwortlich, die Hreflang-Tags auch auszugeben (z.b. per `$seo->getTags()`). Dort ist dann `x-default` auch enthalten.
Während der Weiterleitung hingegen setzt yrewrite selbst die hreflangs (dort per Link-Header statt Meta-Tags, da wir gar keinen Antwort-Body für …
> hreflangs: x-default bei Auto-Sprachweiterleitung

- lib/yrewrite/forward.php
fixes #509
Wenn mehrere Weiterleitungen matchen, wird nun die gewählt, die mehr Params enthält.
@michael-kreatif und @alxndr-w Macht das für euch so Sinn?
Angenommen es wurden diese Weiterleitungen eingerichtet:
1. `/abc`
2. `/abc?foo`
3. `/abc?bar&baz`
Dann gilt:
Aufgerufen | verwendete<br>Weiterleitung | Begründung
--- | --- | ---
`/abc` | 1 | Einziges Matching
`/abc?def` | 1 | Einziges Matching
`/abc?foo&bar` | 2 | Matcht auf 1 und 2 (auf 3 nicht, weil `baz` fehlt), 2 hat aber mehr Params als 1
`/abc?bar&baz&def` | 3 | Matcht auf 1 und 3, aber 3 hat mehr Params
`/abc?foo&bar&baz` | 3 | Alle drei matchen, aber 3 hat die meisten Params
> Weiterleitung mit mehr Params bevorzugt wählen

- setup/.htaccess
mjs (ES6) Module wird von einigen Projekten (vor allem Mozilla) benötigt
> added filetype for mjs to .htaccess

- lang/de_de.lang
- lib/yrewrite/yrewrite.php
- pages/setup.php
Ausgabe einer Fehlermeldung, wenn .htaccess nicht geschrieben werden konnte
Konnte die Datei nicht geschrieben werden, gab es bisher keinen Hinweis darauf. Der bisherige Code ging immer davon aus, dass das Schreiben der Datei immer erfolgreich verläuft.
Es fehlen noch die Anpassungen der anderen Sprachdateien.
> Fix htaccess setup

- lib/yrewrite/seo.php
**Message:** `str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated`
Tritt immer dann auf, wenn Redakteure irgendwo die SEO-Angaben nicht gesetzt haben.
> Fixed deprecation warning

- lib/yrewrite/domain.php
- pages/domains.php
fixes #565, closes #591
Ich finde die Variante in #591 nicht sinnvoll. Eigentlich hatten wir sogar schon Javascript, welches die Kombination beider Optionen verhindern sollte. Das funktionierte aber nicht mehr.
Habe ich repariert und die Abhängigkeit aber umgedreht (und daher auch die Anordnung der Checkboxen).
Und neu wird es aber auch in PHP abgefangen, damit es wirklich nicht mehr zu der Endlosweiterleitung kommt.
> Startsprache-Auto und Startsprache-Hidden als Kombi verhindern

- lib/yrewrite/seo.php
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in src/addons/yrewrite/lib/yrewrite/seo.php on line 177
fixes #570
(finally), other already fixed
> Fix warning: Deprecated: trim(): Passing null to parameter #1
